src/Entity/Header.php
<?php

namespace App\Entity;

use App\Repository\HeaderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HeaderRepository::class)
 */
class Header
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $btnTitle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $btnUrl;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Illustration;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getBtnTitle(): ?string
    {
        return $this->btnTitle;
    }

    public function setBtnTitle(string $btnTitle): self
    {
        $this->btnTitle = $btnTitle;

        return $this;
    }

    public function getBtnUrl(): ?string
    {
        return $this->btnUrl;
    }

    public function setBtnUrl(string $btnUrl): self
    {
        $this->btnUrl = $btnUrl;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->Illustration;
    }

    public function setIllustration(string $Illustration): self
    {
        $this->Illustration = $Illustration;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    /**
     * @Route("/mon-panier", name="cart")
     */
    public function index(Cart $cart, ProductRepository $productRepository): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => $cart->getFull($productRepository),
        ]);
    }

    /**
     * @Route("/cart/add/{id}", name="add_to_cart")
     */
    public function add(Cart $cart, $id): Response
    {
        $cart->add($id);

        return $this->redirectToRoute('products');
    }

    /**
     * @Route("/cart/remove", name="remove_my_cart")
     */
    public function remove(Cart $cart): Response
    {
        $cart->remove();

        return $this->redirectToRoute('products');
    }

    /**
     * @Route("/cart/delete/{id}", name="delete_to_cart")
     */
    public function delete(Cart $cart, $id): Response
    {
        $cart->delete($id);

        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/decrease/{id}", name="decrease_to_cart")
     */
    public function decrease(Cart $cart, $id): Response
    {
        $cart->decrease($id);

        return $this->redirectToRoute('cart');
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Panier - Tout Pour La Gratte{% endblock %}

{% block body %}
<div class='container-list'>
    <h2 class='title'>Mon Panier</h2>
    <div class='col-10 list'>
    {% if cart|length > 0 %}
        <table class='table'>
            <thead>
                <tr>
                    <th colspan='2'>Produit</th>
                    <th>Quantité</th>
                    <th>Prix</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% set total = null %}
            {% for product in cart %}
                <tr>
                    <td><img src='../uploads/{{ product.product.illustration }}' alt='{{ product.product.name }}' class='product'</td>
                    <td class='name'>{{ product.product.name }}</td>
                    <td>
                        <a href='{{ path('decrease_to_cart', {'id': product.product.id}) }}'><img src='{{ asset('img/moins.png') }}' alt='Retirer un produit' class='product-quantity'></a>  X {{ product.quantity }}  <a href='{{ path('add_to_cart', {'id': product.product.id}) }}'><img src='{{ asset('img/plus.png') }}' alt='Ajouter un produit' class='product-quantity'></a>
                    </td>
                    <td>{{ (product.product.price / 100)|number_format(2, ',', ' ')}} €</td>
                    <td>{{ (product.product.price * product.quantity / 100)|number_format(2, ',', ' ') }} €</td>
                    <td><a href='{{ path('delete_to_cart', {'id': product.product.id}) }}'><img src='{{ asset('img/corbeille.png') }}' alt='Supprimer mon produit'></a></td>
                </tr>
                {% set total = total + (product.product.price * product.quantity) %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        <h4 class='title'>Nombre de produits : {{ cart|length }}</h4>
        <h4 class='title'>Total de mon panier : {{ (total / 100)|number_format(2, ',', ' ') }} €</h4>
        <a href='{{ path('order') }}' class='btn submit'>Valider mon panier</a>
    </div>
    {% else %}
        <h4 class='title'>Votre panier est vide</h4>
    {% endif %}
</div>
{% endblock %}